import { useState } from 'react';
import { Check, Loader2, RotateCcw, Sparkles } from 'lucide-react';
import { resumeApi } from '@/api/home.api';
import { notification } from '@/components/common/Notification';
import type { AtsOptimizationResult } from '@/types/content-quality';
import type { Resume } from '@/types/resume';
import type { AtsAnalysisResult } from '@/types/job';
import { getApiErrorMessage } from '@/utils/api-error';

export default function AtsOptimizationPanel({ resumeId, issueId, onResumeChanged }: { resumeId: string; issueId: string; onResumeChanged: (resume: Resume) => void }) {
  const [facts, setFacts] = useState(''); const [result, setResult] = useState<AtsOptimizationResult | null>(null); const [draft, setDraft] = useState(''); const [loading, setLoading] = useState(false); const [versionId, setVersionId] = useState<string | null>(null); const [ats, setAts] = useState<AtsAnalysisResult | null>(null); const [previousScore, setPreviousScore] = useState<number | null>(null);
  const generate = async () => { setLoading(true); try { const response = await resumeApi.optimizeAtsIssue(resumeId, { issueId, userFacts: facts }); if (response.code !== 200) throw new Error(response.message); setResult(response.data); setDraft(response.data.mode === 'suggestion' ? response.data.suggestedText : ''); } catch (cause) { notification.error(getApiErrorMessage(cause, 'ATS 优化建议生成失败')); } finally { setLoading(false); } };
  const apply = async () => { if (!draft.trim()) return notification.error('建议文本不能为空'); setLoading(true); try { const response = await resumeApi.applyAtsOptimization(resumeId, { issueId, suggestedText: draft.trim() }); if (response.code !== 200) throw new Error(response.message); setVersionId(response.data.versionId); setPreviousScore(response.data.previousScore); setAts(response.data.ats); onResumeChanged(response.data.resume); notification.success('ATS 建议已应用，并已创建版本快照'); } catch (cause) { notification.error(getApiErrorMessage(cause, '应用建议失败')); } finally { setLoading(false); } };
  const restore = async () => { if (!versionId) return; setLoading(true); try { const response = await resumeApi.restoreVersion(resumeId, versionId); if (response.code !== 200) throw new Error(response.message); onResumeChanged(response.data); setVersionId(null); setAts(null); notification.success('已恢复应用前版本'); } catch (cause) { notification.error(getApiErrorMessage(cause, '恢复版本失败')); } finally { setLoading(false); } };
  const resolved = ats ? !ats.issues.some((item) => item.id === issueId) : false; const delta = ats && previousScore !== null ? ats.score - previousScore : null;
  return <div className="flex h-full flex-col bg-white"><header className="border-b p-4"><div className="flex items-center gap-2"><Sparkles size={18} className="text-blue-600" /><h2 className="font-semibold">ATS 字段修正</h2></div><p className="mt-1 text-xs text-gray-500">仅修改可定位的现有字段；结构缺失问题请使用普通编辑器补充。</p></header><div className="flex-1 space-y-4 overflow-auto p-4">{result && <blockquote className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-gray-700">{result.originalText}</blockquote>}{result?.mode === 'needs_input' && <ul className="list-disc rounded-lg border p-3 pl-8 text-sm text-gray-600">{result.questions.map((q) => <li key={q}>{q}</li>)}</ul>}<label className="block text-sm font-medium text-gray-700">补充真实内容<textarea value={facts} onChange={(e) => setFacts(e.target.value)} className="mt-2 min-h-28 w-full rounded-lg border p-3 text-sm" placeholder="填写该字段应表达的真实信息，不要编造。" /></label><button disabled={loading || Boolean(versionId)} onClick={() => void generate()} className="flex w-full items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-medium text-white disabled:opacity-50">{loading ? <Loader2 size={16} className="animate-spin" /> : <Sparkles size={16} />}生成修正建议</button>{result?.mode === 'suggestion' && <section className="space-y-3 rounded-lg border border-blue-200 bg-blue-50 p-4"><textarea value={draft} disabled={Boolean(versionId)} onChange={(e) => setDraft(e.target.value)} className="min-h-32 w-full rounded-lg border bg-white p-3 text-sm disabled:bg-gray-100" /><p className="text-sm text-gray-700">{result.reason}</p>{versionId ? <div className="space-y-2 rounded border border-emerald-200 bg-white p-3"><div className="flex justify-between"><span className="flex items-center gap-1 text-xs text-emerald-700"><Check size={14} />已应用并创建快照</span><button onClick={() => void restore()} className="flex items-center gap-1 text-sm text-emerald-700"><RotateCcw size={14} />撤销</button></div>{ats && <p className={`text-xs ${resolved ? 'text-emerald-700' : 'text-amber-700'}`}>ATS {previousScore} → {ats.score}{delta !== null && `（${delta >= 0 ? '+' : ''}${delta}）`}；{resolved ? '原问题已解决。' : '原问题仍存在。'}</p>}</div> : <button disabled={loading} onClick={() => void apply()} className="rounded bg-blue-600 px-3 py-2 text-sm text-white">应用建议</button>}</section>}</div></div>;
}
